export const LOGIN_USER = "login_user"
export const DASHBOARD = "user_dashboard"
export const CREATE = "user_create"
export const AUTH = "user_auth"
export const EDIT = "user_edit"
export const SINGLE_PRODUCT = "single_product"
export const UPDATE_PRODUCT = "update_product"